### ISSUE TITLE
咦？mengskysama打算重新开始维护这个项目了？

### ISSUE THREAD

**Issue by falseen** [mengskysama/shadowsocks-rm#1]
好久没见你更新了

**Comment by mengskysama** [comment]
上游不更新了，这个分支暂时用来修正使用过程发现的已知bug。
看情况manyuser分支改动比较大等下次release重新拉一个分支。

**Comment by peinhu** [comment]
兹瓷

**Comment by falseen** [comment]
嗯，现在只剩breakwa11那里还在更新，没事来聊聊吧  https://gitter.im/breakwa11/shadowsocksr
