### ISSUE TITLE
shadowsocks-rm加密方式

### ISSUE THREAD

**Issue by bh1xaq** [mengskysama/shadowsocks-rm#18]

**Comment by TXisfine** [comment]
问题解决：

manyuser 版Ss默认的加密模式是：rc4-md5 如需修改请自行编辑/shadowsocks/shadowsocks/config.json的method项，其余请勿修改。

**Comment by raphaelsoul** [comment]
最新的commit里放在了config.py里。

**Comment by mengskysama** [comment]
yea..
