### ISSUE TITLE
Inaccurate Data Recording

### ISSUE THREAD

**Issue by fsgmhoward** [mengskysama/shadowsocks-rm#23]
I am using Shadowsocks-rm Manyuser whose latest commit is b9766ce on 12 Jan 2016.

I believed that my server has used up more than 100 GBytes but the record at the database is only 24 GBytes. What's more, Shadowsocks-rm Manyuser does not report the upload data (as it did in the previous version)

**Comment by mengskysama** [comment]
fixed
