### ISSUE TITLE
IPv6的监听有问题

### ISSUE THREAD

**Issue by fsgmhoward** [mengskysama/shadowsocks-rm#27]
如题，当我设置监听地址为`[::]`的时候，数据库会无限读取（add {serverport....}会无限输出）并且不会监听任何端口。

**Comment by zuoruizhi** [comment]
这样写就可以了
#BIND IP
#if you want bind ipv4 and ipv6 '::'
#if you want bind all of ipv4 if '0.0.0.0'
#if you want bind all of if only '4.4.4.4'
SS_BIND_IP = '::'
SS_METHOD = 'aes-256-cfb'

[root@li715-116 shadowsocks]# netstat -lanp|grep python
tcp 0 0 :::1025 :::\* LISTEN 24954/python

udp 0 0 127.0.0.1:63333 0.0.0.0:\* 24954/python

udp 0 0 :::1025 :::\* 24954/python

unix 2 [ ACC ] STREAM LISTENING 182557 2147/python /tmp/supervisor.sock.2147
[root@li715-116 shadowsocks]#

同[#32](https://github.com/mengskysama/shadowsocks-rm/issues/32)

**Comment by fsgmhoward** [comment]
@zuoruizhi 谢谢，问题解决了。
