### ISSUE TITLE
能够修改数据库表名吗？

### ISSUE THREAD

**Issue by ghost** [mengskysama/shadowsocks-rm#35]
现在默认的是user，下一个版本可以修改这个 user 吗，或者自己修改源文件，具体需要修改那些可以告诉一下吗？谢谢

**Comment by wodedajiba** [comment]
db_transfer.py

**Comment by zuoruizhi** [comment]
为什么回复完又删掉了？
就是修改dbtransfer.py

def push_db_all_user(self):
        dt_transfer = self.get_servers_transfer()
        query_head = 'UPDATE user'
        query_sub_when = ''
        query_sub_when2 = ''
        query_sub_in = None
        last_time = time.time()
        for id in dt_transfer.keys():
            query_sub_when += ' WHEN %s THEN u+%s' % (id, 0) # all in d
            query_sub_when2 += ' WHEN %s THEN d+%s' % (id, dt_transfer[id])
            if query_sub_in is not None:
                query_sub_in += ',%s' % id
            else:
                query_sub_in = '%s' % id
        if query_sub_when == '':
            return
        query_sql = query_head + ' SET u = CASE port' + query_sub_when + \
                    ' END, d = CASE port' + query_sub_when2 + \
                    ' END, t = ' + str(int(last_time)) + \
                    ' WHERE port IN (%s)' % query_sub_in
        #print query_sql
        conn = cymysql.connect(host=config.MYSQL_HOST, port=config.MYSQL_PORT, user=config.MYSQL_USER,
                               passwd=config.MYSQL_PASS, db=config.MYSQL_DB, charset='utf8')
        cur = conn.cursor()
        cur.execute(query_sql)
        cur.close()
        conn.commit()
        conn.close()

这一段是更新用户流量信息

 @staticmethod
    def pull_db_all_user():
        conn = cymysql.connect(host=config.MYSQL_HOST, port=config.MYSQL_PORT, user=config.MYSQL_USER,
                               passwd=config.MYSQL_PASS, db=config.MYSQL_DB, charset='utf8')
        cur = conn.cursor()
        cur.execute("SELECT port, u, d, transfer_enable, passwd, switch, enable FROM user")
        rows = []
        for r in cur.fetchall():
            rows.append(list(r))
        cur.close()
        conn.close()
        return rows

这一段是查询用户信息

**Comment by ghost** [comment]
谢谢。。第一次用这个。连删除了都知道。。好恐怖。。我怕我回复错了误导其他用户。

**Comment by zuoruizhi** [comment]
@wodedajiba 关注后有邮件提醒的

**Comment by ghost** [comment]
@zuoruizhi  大神，谢谢回答，我想问下 数据库中的 switch，enable 这两个字段是用来干啥的

**Comment by zuoruizhi** [comment]
是否启用账号    现在两个字段意义一样

**Comment by zuoruizhi** [comment]
@wodedajiba 在这判断的  也是dbtransfer.py 
def del_server_out_of_bound_safe(rows):

 if row[5] == 0 or row[6] == 0:
                    #stop disable or switch off user
                    logging.info('db stop server at port [%s] reason: disable' % (row[0]))
                    DbTransfer.send_command('remove: {"server_port":%s}' % row[0])

**Comment by ghost** [comment]
@zuoruizhi 感谢感谢

**Comment by ghost** [comment]
@zuoruizhi  您好，我想请问下，如何关闭默认打开的UDP呢？

**Comment by tlzzu** [comment]
请问 我安装后启动时出现这个错误：
[root@localhost shadowsocks]# python servers.py
Traceback (most recent call last):
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 197, in thread_push
    DbTransfer.get_instance().push_db_all_user()
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 108, in push_db_all_user
    response = urllib2.urlopen(req)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(_args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(_args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 401: Unauthorized
WARNING:root:db thread except:HTTP Error 401: Unauthorized
不知道是什么原因，怎么解决，ss-panel运行正常，站点也起来了，但是根据站点中显示的配置，不能翻墙，，，求解

**Comment by zuoruizhi** [comment]
ss-panel版本多少，传下配置文件，看报错mu api有问题

**Comment by tlzzu** [comment]
[root@localhost shadowsocks]# python servers.py
Traceback (most recent call last):
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 197, in thread_push
    DbTransfer.get_instance().push_db_all_user()
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 98, in push_db_all_user
    response = urllib2.urlopen(req)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(_args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(_args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found
WARNING:root:db thread except:HTTP Error 404: Not Found

# ERROR:root:[Errno 104] Connection reset by peer

以下是config.py文件：
[root@localhost shadowsocks]# vim config.py
import logging

#Config
MYSQL_HOST = 'localhost'
MYSQL_PORT = 3306
MYSQL_USER = 'root'
MYSQL_PASS = '123456789xxc'
MYSQL_DB = 'sspanel'

MANAGE_PASS = 'aslouyd58jdgf'
#if you want manage in other server you should set this value to global ip
MANAGE_BIND_IP = '127.0.0.1'
#make sure this port is idle
MANAGE_PORT = 23333

PANEL_VERSION = 'V3' # V2 or V3. V2 not support API
API_URL = 'http://vpsmu.demo.com'
API_PASS = 'aslouyd58jdgf'
NODE_ID = '1'
CHECKTIME = 15
SYNCTIME = 600

#BIND IP
#if you want bind ipv4 and ipv6 '[::]'
#if you want bind all of ipv4 if '0.0.0.0'
#if you want bind all of if only '4.4.4.4'
SS_BIND_IP = '0.0.0.0'
SS_METHOD = 'rc4-md5'

#LOG CONFIG
LOG_ENABLE = False
LOG_LEVEL = logging.DEBUG
LOG_FILE = '/var/log/shadowsocks.log'

# 

以下是.env文件：
//  ss-panel v3 ▒~E~M置
//
// !!! 修▒~T▒此key为▒~Z~O▒~\▒▒~W符串确▒~]▒~Q▒~Y▒~I▒~E▒ !!!
key = 'aslouyd58jdgf'
env = 'prod'  // 正▒~O▒~N▒▒~C请▒~]▒~L~Aenv为prod确▒~]▒~I▒~E▒
debug =  'false'  //  正▒~O▒~N▒▒~C请确▒~]为false
appName = 'ss-panel3'             //▒~Y▒~B▒▒~P~M称
baseUrl = 'http://vpsmu.demo.com'            // ▒~Y▒~B▒▒~\▒▒~]~@
timeZone = 'PRC'        // RPC 天▒~~]▒~W▒▒~W▒  UTC ▒| ▒▒~^~W▒~W▒▒~W▒
pwdMethod = 'md5'       // ▒~F▒| ~A▒~J| ▒~F   ▒~O▒▒~@~I md5,sha256
salt = ''               // ▒~F▒| ~A▒~J| ▒~F▒~T▒▒~L▒~N▒~W▒▒~I~H▒~M~G级请▒~U~Y空
theme    = 'default'   // 主▒~X
// v3.4 ▒~P~N使▒~T▒ session代▒~[▒authDriver
// session,cache  ▒~O▒▒~@~I file/redis
session = 'file'
cache   = 'file'
tokenDriver = 'db'
// mu key ▒~T▒▒~N▒| ▒▒~Lss-go mu▒~Z~D请▒~B
muKey = 'aslouyd58jdgf'
// ▒~B▒件
mailDriver = 'mailgun'   // mailgun   #smtp▒~M▒~\▒▒~T▒▒~L~A,▒~E▒~[▒~K▒~U

// 注▒~F~L▒~Y~P▒~H▒,▒~O天▒~O个ip▒~C▒注▒~F~L▒~Z~D次▒~U▒
ipDayLimit = '10'

// ▒~B▒箱▒~L▒~A设置
emailVerifyEnabled = 'false' // ▒~X▒▒~P▒▒~@▒~P▒注▒~F~L▒~W▒▒~B▒箱▒~L▒~A (true:▒~@▒~P▒ faa
lse:▒~E▒▒~W▒)
emailVerifyCodeLength = '8'  // ▒~B▒箱▒~L▒~A代▒| ~A▒~U▒度
emailVerifyTTL = '30'        // ▒~L▒~A代▒| ~A▒~~I▒~U~H▒~W▒▒~W▒ ▒~M~U▒~M▒~H~F▒~R~_

// ▒~T▒▒~H▒签▒~H▒设置
checkinTime = '22'      // 签▒~H▒▒~W▒▒~Z~T▒~W▒▒~W▒ ▒~M~U▒~M▒~O▒~W▒
checkinMin = '93'       // 签▒~H▒▒~~@▒~Q▒~A▒~G~O ▒~M~U▒~MMB
checkinMax = '97'       // 签▒~H▒▒~~@▒~Z▒~A▒~G~O

//
defaultTraffic = '1'      // ▒~T▒▒~H▒▒~H~]▒~K▒~A▒~G~O ▒~M~U▒~MGB
// 注▒~F~L▒~P~N▒~N▒▒~W▒~Z~D▒~B~@请▒| ~A▒~U▒▒~G~O
inviteNum = '0'

// 记▒~U▒~A▒~G~O▒~W▒▒~W▒~H▒dynamodb ,beta,请▒~K▒▒~@▒~P▒
log_traffic_dynamodb = 'false'

# database ▒~U▒▒~M▒▒~S▒~E~M置

db_driver = 'mysql'
db_host = 'localhost'
db_port = '3306'
db_database = 'sspanel'
db_username = 'root'
db_password = '123456789xxc'
db_charset = 'utf8'
db_collation = 'utf8_general_ci'
db_prefix = ''

# redis

redis_scheme = 'tcp'
redis_host = '127.0.0.1'
redis_port = '6379'
redis_database = '0'
redis_pass = ''

# mailgun

mailgun_key = ''
mailgun_domain = ''
mailgun_sender = ''

# smtp

smtp_host = ''
smtp_username = ''
smtp_port = ''
smtp_name = ''
smtp_sender = ''
smtp_passsword = ''
smtp_ssl = 'true'

# aws

aws_access_key_id = ''
aws_secret_access_key = ''
aws_region = 'ap-northeast-1'
aws_ses_region = 'us-east-1'
aws_ses_sender = ''

---

现在是程序能运行（能够代理，但没有记录使用流量）但是ss-panel上面的在线人数以及使用流量统计都没有，不知道是哪里错了。而且代理很不稳定，有时无法翻墙，应该是有错误，然后再次执行一下python servers.py就又可以代理了，但是DbTransfer.get_instance().push_db_all_user()的错误依然在。
不知道应该怎么解决

**Comment by zuoruizhi** [comment]
API_URL 错了   写成
API_URL = 'http://vpsmu.demo.com/mu'

**Comment by tlzzu** [comment]
改好了，现在是可以稳定的代理了，但是流量统计、节点在线人数还是没有，再次运行出现这个错误：
[root@localhost shadowsocks]# python servers.py
ERROR:root:[Errno 111] Connection refused

**Comment by zuoruizhi** [comment]
流量统计、节点在线人数更新间隔是SYNCTIME = 600控制的   单位秒

**Comment by tlzzu** [comment]
现在过了10分钟，还是没有流量统计，使用代理是出现的错误如下：

Traceback (most recent call last):
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 197, in thread_push
    DbTransfer.get_instance().push_db_all_user()
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 98, in push_db_all_user
    response = urllib2.urlopen(req)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(_args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(_args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: Internal Server Error
WARNING:root:db thread except:HTTP Error 500: Internal Server Error
ERROR:root:[Errno 111] Connection refused
ERROR:root:[Errno 104] Connection reset by peer
WARNING:root:timed out: 74.125.28.188:5228
WARNING:root:timed out: www.googletagmanager.com:443
WARNING:root:timed out: www.google.com:443
WARNING:root:timed out: accounts.google.com:443
WARNING:root:unsupported addrtype 174, maybe wrong password or encryption method
ERROR:root:[1025]can not parse header when handling connection from 104.194.76.26:37942
Traceback (most recent call last):
  File "../shadowsocks/tcprelay.py", line 328, in _handle_stage_addr
    raise Exception('[%s]can not parse header'%(self._config['server_port']))
Exception: [1025]can not parse header
WARNING:root:unsupported addrtype 0, maybe wrong password or encryption method
ERROR:root:[1026]can not parse header when handling connection from 104.194.76.26:40266
Traceback (most recent call last):
  File "../shadowsocks/tcprelay.py", line 328, in _handle_stage_addr
    raise Exception('[%s]can not parse header'%(self._config['server_port']))
Exception: [1026]can not parse header
WARNING:root:timed out: ssl.google-analytics.com:443
WARNING:root:timed out: 118.194.55.213:5223
WARNING:root:timed out: 74.125.28.188:5228
ERROR:root:[Errno 104] Connection reset by peer
ERROR:root:[Errno 111] Connection refused
WARNING:root:timed out: 14.17.42.31:443
ERROR:root:[Errno 111] Connection refused
ERROR:root:[Errno 111] Connection refused
ERROR:root:[Errno 111] Connection refused
WARNING:root:timed out: ssl.google-analytics.com:443
ERROR:root:[Errno 104] Connection reset by peer
ERROR:root:[Errno 104] Connection reset by peer
WARNING:root:unsupported addrtype 143, maybe wrong password or encryption method
ERROR:root:[1025]can not parse header when handling connection from 123.117.172.17:31889
Traceback (most recent call last):
  File "../shadowsocks/tcprelay.py", line 328, in _handle_stage_addr
    raise Exception('[%s]can not parse header'%(self._config['server_port']))
Exception: [1025]can not parse header
ERROR:root:[Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 197, in thread_push
    DbTransfer.get_instance().push_db_all_user()
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 98, in push_db_all_user
    response = urllib2.urlopen(req)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(_args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(_args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: Internal Server Error
WARNING:root:db thread except:HTTP Error 500: Internal Server Error
ERROR:root:[Errno 104] Connection reset by peer

# ERROR:root:[Errno 104] Connection reset by peer

是python 服务 数据库没有连接好吗？

**Comment by tlzzu** [comment]
![image](https://cloud.githubusercontent.com/assets/13477114/18500867/2830d8b6-7a7e-11e6-9218-9d65c9cfd7fd.png)
vps内存占用也很高

**Comment by ghost** [comment]
大哥哥，可以新开个贴么。问的都不是重点啊。你自己各种没有配置好，应该是。

**Comment by zuoruizhi** [comment]
HTTPError: HTTP Error 500: Internal Server Error

**Comment by zuoruizhi** [comment]
@tlzzu 新开个贴@我，现在 Merged的代码不全，我正好看下

**Comment by tlzzu** [comment]
@zuoruizhi
新帖在这个位置，不知道怎么的 无法@ 你
https://github.com/mengskysama/shadowsocks-rm/issues/54
