### ISSUE TITLE
rm

### ISSUE THREAD

**Issue by q158073378252010** [mengskysama/shadowsocks-rm#42]
下面是 supervisor 配置 。这样配置不能运行，似乎必须使用 "-c" 参数 。但是servers.py 似乎不需要这个 .conf
请教如何运行？
[program:ss-p]
command=python /home/shadowsocks-rm/shadowsocks/servers.py
autorestart=true
user=ssuser
redirect_stderr=true
stdout_logfile=/var/log/ss-p.log
stdout_logfile_maxbytes=10MB
stderr_logfile=/var/log/ss-p.err.log
stderr_logfile_maxbytes=1MB

**Comment by raphaelsoul** [comment]
用systemd吧

**Comment by q158073378252010** [comment]
@raphaelsoul 感谢你的建议，
