### ISSUE TITLE
manyuser 报错UrlError:  Name or service not known

### ISSUE THREAD

**Issue by adamin1990** [mengskysama/shadowsocks-rm#44]
打印出url发现访问的python访问的地址是：
http://domain/mu/nodes/1/online_count?key=mupass
/domain/mu 这个地方是在config.py里面配置的 这个地方需要怎么配置 ？

我把domain替换成服务器的ip后提示 `HTTPError: HTTP Error 401: Unauthorized
WARNING:root:db thread except:HTTP Error 401: Unauthorized
`

**Comment by adamin1990** [comment]
问题解决了： cofig.py里面的API_URL 需要更改为 自己的域名/mu  ;API_PAS需要与sspanel .env里面的mukey一致。

**Comment by foonsun** [comment]
请问 @adamin1990 修改后运行python server.py 没有上面的错误了，但是什么LOG都没有，请问是什么原因啊？

**Comment by adamin1990** [comment]
@foonsun  log在config.py最后面配置，可以用 `cat /var/log/shadowsocks.log` 查看log

**Comment by mengskysama** [comment]
这个代码我也没有经过严格测试，而且有人反映经常死掉。:(

**Comment by artus-dnomaid** [comment]
能否不支持这个ss-pannel？

**Comment by zuoruizhi** [comment]
已修复，标准版前端无问题
