### ISSUE TITLE
Manyuser Branch Readme is missing socket management doc

### ISSUE THREAD

**Issue by forest2087** [mengskysama/shadowsocks-rm#5]
和原来一样吗？

Manage socket

Manage server work in UDP at MANAGE_BIND_IP MANAGE_PORT

use MANAGE_PASS:port:passwd:0 to del a server at port port

use MANAGE_PASS:port:passwd:1 to run a server at port port password is passwd

Python Eg:

udpsock.sendto('MANAGE_PASS:65535:123456:1', (MANAGE_BIND_IP, MANAGE_PORT))
PHP Eg:

$sock = socket_create(AF_INET, SOCK_DGRAM, SOL_UDP);
$msg = 'MANAGE_PASS:65535:123456:1';
$len = strlen($msg);
socket_sendto($sock, $msg, $len, 0, MANAGE_BIND_IP, MANAGE_PORT);
socket_close($sock);

**Comment by mengskysama** [comment]
理论只要通过操作数据库就能够开启了，不过目前还没时间完善。

**Comment by forest2087** [comment]
OK thanks
