### ISSUE TITLE
Manyuser Branch 不写log？

### ISSUE THREAD

**Issue by forest2087** [mengskysama/shadowsocks-rm#6]
Mnayuser branch 好像logging没用啊, 就是指定--log-file 也不行。。。 
哪位帮debug一下，我没用过python

**Comment by forest2087** [comment]
好吧我找到solution了，
加上 logging.basicConfig(filename='example.log',level=logging.DEBUG)
或者 filename=config['log-file']

https://docs.python.org/2/howto/logging.html

**Comment by 95289527** [comment]
@forest2087  麻烦可以提个pull不 我也是没有记录log

**Comment by forest2087** [comment]
@nqzhang OK, maybe later this week.
