### ISSUE TITLE
ImportError: No module named cymysql

### ISSUE THREAD

**Issue by leapsea** [mengskysama/shadowsocks-rm#64]
File "servers.py", line 35, in <module>
  from dbtransfer import DbTransfer
File "/srv/www/html/shadowsocks-rm/shadowsocks/dbtransfer.py", line 5, in <module>
  import cymysql
ImportError: No module named cymysql

图片：
http://blog.leapsea.com/content/uploadfile/201610/bf681476418193.png

环境：Ubuntu14
Python 2.7.6
已安装 cymysql，但仍报错

**Comment by zuoruizhi** [comment]
你怎么安的

**Comment by leapsea** [comment]
https://iforday.com/160.html
按照这个教程安装的

安装ssr之前先安装了这个。
https://github.com/seatom/crysadm
这个也是使用了python，可能出现了版本不兼容的情况

**Comment by zuoruizhi** [comment]
你装的是ssr版本还是这个rm的

**Comment by leapsea** [comment]
rm版本的。

**Comment by usc** [comment]
根目录即 ./shadowsocksr，这个是多用户的，会用到cymysql模块
子目录即 ./shadowsocksr/shadowsocks，这个才是单用户的
所以单用户的启动是 python ./shadowsocksr/shadowsocks/server.py  xxx
