### ISSUE TITLE
python servers.py error

### ISSUE THREAD

**Issue by crazcdll** [mengskysama/shadowsocks-rm#67]
![error](https://cloud.githubusercontent.com/assets/2687656/20656723/a31bd48c-b56a-11e6-9ca5-74aed5d84fb4.png)

运行 servers.py  文件时报错，查了好久不知道怎么弄。。
用的 V3 版本的 ss-panel，ubuntu，python 版本 2.7.12

谢谢啦！

**Comment by zuoruizhi** [comment]
DNS解析错误，
echo "nameserver 8.8.8.8" >> /etc/resolv.conf 
最好发下配置文件。

**Comment by crazcdll** [comment]
这个是 config.py 
```
import logging

#Config
MYSQL_HOST = '127.0.0.1'
MYSQL_PORT = 3306
MYSQL_USER = 'root'
MYSQL_PASS = 'google'
MYSQL_DB = 'shadowsocks'

MANAGE_PASS = 'passwd'
#if you want manage in other server you should set this value to global ip
MANAGE_BIND_IP = '127.0.0.1'
#make sure this port is idle
MANAGE_PORT = 23333

PANEL_VERSION = 'V3' # V2 or V3. V2 not support API
API_URL = 'http://domain/mu'
API_PASS = 'mupass'
NODE_ID = '1'
CHECKTIME = 15
SYNCTIME = 600

#BIND IP
#if you want bind ipv4 and ipv6 '[::]'
#if you want bind all of ipv4 if '0.0.0.0'
#if you want bind all of if only '4.4.4.4'
SS_BIND_IP = '0.0.0.0'
SS_METHOD = 'rc4-md5'

#LOG CONFIG
LOG_ENABLE = False
LOG_LEVEL = logging.DEBUG
LOG_FILE = '/var/log/shadowsocks.log'
```
别的文件我没有修改。

我刚才试了 @zuoruizhi 你说的方法，还是不行。。

**Comment by zuoruizhi** [comment]
PANEL_VERSION = 'V3' # V2 or V3. V2 not support API
API_URL = 'http://domain/mu'
API_PASS = 'mupass'
NODE_ID = '1'
CHECKTIME = 15
SYNCTIME = 600


这一段需要修改的啊

**Comment by crazcdll** [comment]
那该怎么修改啊？

抱歉，我找的教程上没有写这一段怎么修改

[一个新手向的 SS-Panel 部署教程](https://mechanus.io/yi-ge-xin-shou-xiang-de-ss-panel-bu-shu-jiao-cheng/)

**Comment by zuoruizhi** [comment]
想要记录流量信息的话就
API_URL = 'http://访问地址/mu'     
/mu不能省略
API_PASS  参考前端    配制成一样的
NODE_ID  看前端    ID是多少写多少



不想记录PANEL_VERSION = 'V2'

**Comment by zuoruizhi** [comment]
WIKI  https://github.com/mengskysama/shadowsocks-rm/wiki/%E5%85%B3%E4%BA%8Emu-API-V1%E7%89%88%E6%9C%AC%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E

**Comment by crazcdll** [comment]
恩恩，我也在查这一段的配置
[ShadowsocksR 多用户版安装教程](https://github.com/breakwa11/shadowsocks-rss/wiki/Server-Setup(manyuser-with-mysql))

> 要注意sspanelv3必须正确填写node_id才能正常使用，并且在填写该ID前，必须在面板上已经添加好该节点，以确定节点ID后，再在此处填写。

有这么一段，这里说的  必须在面板上已经添加好该节点，以确定节点ID后，再在此处填写。
可以我在 ss-panel 的 .env 里面没看到 node_id 的设置选项啊。
这个该怎么设置呢？

谢谢！

**Comment by zuoruizhi** [comment]
node id是后端的   与前端配置文件无关

**Comment by crazcdll** [comment]
额。。那你说  NODE_ID 看前端 ID是多少写多少   怎么理解啊？我去哪里查这个 node_id 呀？

**Comment by zuoruizhi** [comment]
你添加节点了吗    添加之后就能看到了啊

**Comment by zuoruizhi** [comment]
![image](https://cloud.githubusercontent.com/assets/8614920/20657601/27935efe-b572-11e6-962a-361ceb7a6b30.png)

**Comment by crazcdll** [comment]
我正在 前台添加节点  但是报500错误

**Comment by zuoruizhi** [comment]
问前端那边去吧...

**Comment by crazcdll** [comment]
节点添加成功了，不过是随意写的IP地址可以吗？

![snipaste20161128_141119](https://cloud.githubusercontent.com/assets/2687656/20657981/e6e0806e-b574-11e6-90fe-8e977995c002.png)

![snipaste20161128_141132](https://cloud.githubusercontent.com/assets/2687656/20657986/eaba8a9a-b574-11e6-81d8-0c08acc590cf.png)

然后 config.py 内容如下

```
import logging

#Config
MYSQL_HOST = '127.0.0.1'
MYSQL_PORT = 3306
MYSQL_USER = 'root'
MYSQL_PASS = 'google'
MYSQL_DB = 'shadowsocks'

MANAGE_PASS = 'passwd'
#if you want manage in other server you should set this value to global ip
MANAGE_BIND_IP = '127.0.0.1'
#make sure this port is idle
MANAGE_PORT = 23333

PANEL_VERSION = 'V3' # V2 or V3. V2 not support API
API_URL = '45.56.XX.XX/mu'
API_PASS = 'mupass'
NODE_ID = '1'
CHECKTIME = 15
SYNCTIME = 600

#BIND IP
#if you want bind ipv4 and ipv6 '[::]'
#if you want bind all of ipv4 if '0.0.0.0'
#if you want bind all of if only '4.4.4.4'
SS_BIND_IP = '0.0.0.0'
SS_METHOD = 'rc4-md5'

#LOG CONFIG
LOG_ENABLE = False
LOG_LEVEL = logging.DEBUG
LOG_FILE = '/var/log/shadowsocks.log'
```
其中，API_URL = '45.56.XX.XX/mu' 这里的IP是我VPS的IP 也是我访问 ss-panel 的地址。
这么写 对吗？

然后我运行 python servers.py 不报之前那个错误了，但是也没反应了。我等了会儿就按 ctrl+c 退出了。
```
root@ubuntu:/var/www/shadowsocks-rm/shadowsocks# python servers.py
^CTraceback (most recent call last):
  File "servers.py", line 63, in <module>
    main()
  File "servers.py", line 59, in main
    time.sleep(100)
KeyboardInterrupt

```

**Comment by zuoruizhi** [comment]
可以   正常

**Comment by crazcdll** [comment]
就是说，目前来看我搞定这一步了是吧？

谢谢啦！！ ^_^

**Comment by zuoruizhi** [comment]
没反应是正常的      通常调用supervisord来监控ss服务，   如果想要手动运行可以
nohup  python servers.py &
来运行，会自动在后台运行，关掉shell也没事

**Comment by crazcdll** [comment]
嗯嗯！
恍然大悟了！

想起来之前搞得Linux相关的东东了！
谢谢！

我刚才看了下，nohup.out 里面有信息
```
root@ubuntu:/var/www/shadowsocks-rm/shadowsocks# tail -f nohup.out
  File "/var/www/shadowsocks-rm/shadowsocks/dbtransfer.py", line 119, in push_db_all_user
    response = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 421, in open
    protocol = req.get_type()
  File "/usr/lib/python2.7/urllib2.py", line 283, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: 45.56.XX.XX/mu/nodes/1/online_count?key=mupass
WARNING:root:db thread except:unknown url type: 45.56.XX.XX/mu/nodes/1/online_count?key=mupass

```
跟之前报错的前一段时一样的。

这个是说我填写的节点地址不正确的意思吗？
我如果正确填写 节点信息 是不是就可以了？

**Comment by zuoruizhi** [comment]
API_URL = 'http://45.56.XX.XX/mu'

**Comment by crazcdll** [comment]
额。。我修改了API_URL 后，再运行 servers.py 会报错
```
ERROR:root:[Errno 98] Address already in use
ERROR:root:can not bind to manager address
```

我怎么删掉之前添加的信息呀？

**Comment by zuoruizhi** [comment]
reboot

**Comment by crazcdll** [comment]
不行啊。。
我 reboot 了
改成了 API_URL = 'http://45.56.XX.XX/mu'
还是报错呀 

```
root@ubuntu:/var/www/shadowsocks-rm/shadowsocks# tail -f nohup.out
  File "/var/www/shadowsocks-rm/shadowsocks/dbtransfer.py", line 119, in push_db_all_user
    response = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 421, in open
    protocol = req.get_type()
  File "/usr/lib/python2.7/urllib2.py", line 283, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: 45.56.XX.XX/mu/nodes/1/online_count?key=mupass
WARNING:root:db thread except:unknown url type: 45.56.XX.XX/mu/nodes/1/online_count?key=mupass
```

**Comment by crazcdll** [comment]
难道直接写IP不行吗？需要改一个域名？

**Comment by crazcdll** [comment]
刚才注册了一个域名，绑定后，再给DNS添加 8.8.8.8 和 8.8.4.4 后，启动 nohup python servers.py & 没有错误信息了！

谢谢 @zuoruizhi 今天下午一直在帮我解决问题！

**Comment by prncoprs** [comment]
@zcdll 
请问之前你遇到 前台添加节点 但是报500错误 的这个问题是怎么解决的呀？

**Comment by crazcdll** [comment]
@prncoprs 抱歉，没有遇到过
