### ISSUE TITLE
多节点写入同一个数据库，导致慢查询时有发生

### ISSUE THREAD

**Issue by javacty** [mengskysama/shadowsocks-rm#7]
我就用中文了，英语太烂：
        非常感谢mengskysama大大提供的程序，我现在是这样一个场景：
我在国外的3个vps上部署了shadowsocks-rm manyuser版，管理网站ss-panel放在国内的vps，数据库也是放在这个国内的vps上，3个国外的vps共用网站的数据库。

问题：
        网站时而会卡一下，大部分时间还比较快，mysql做了下慢查询记录：
Time: 151209 11:08:25
User@Host: ss_lrb[ss_lrb] @  [133.130.0.0]
Thread_id: 3104  Schema: shadowsocks  QC_hit: No
Query_time: 61.113150  Lock_time: 0.000190  Rows_sent: 1512  Rows_examined: 1512
SET timestamp=1449630505;
SELECT port, u, d, transfer_enable, passwd, switch, enable FROM user;

Time: 151209 11:08:44
User@Host: ss_xmg[ss_xmg] @  [163.44.0.0]
Thread_id: 3145  Schema: shadowsocks  QC_hit: No
Query_time: 60.193568  Lock_time: 0.000201  Rows_sent: 904  Rows_examined: 904
SET timestamp=1449630524;
SELECT port, u, d, transfer_enable, passwd, switch, enable FROM user;
Time: 151209 11:11:06
User@Host: ss_xmg[ss_xmg] @  [163.44.0.0]
Thread_id: 3259  Schema: shadowsocks  QC_hit: No
Query_time: 24.040012  Lock_time: 0.000225  Rows_sent: 1512  Rows_examined: 1512
SET timestamp=1449630666;
SELECT port, u, d, transfer_enable, passwd, switch, enable FROM user;

Time: 151209 11:12:13
User@Host: ss_xmg[ss_xmg] @  [163.44.0.0]
Thread_id: 3307  Schema: shadowsocks  QC_hit: No
Query_time: 8.165709  Lock_time: 0.000247  Rows_sent: 1512  Rows_examined: 1512
SET timestamp=1449630733;
SELECT port, u, d, transfer_enable, passwd, switch, enable FROM user;

不知是不是因为持续的update，清空了select缓存并且阻塞了select，我想:
shadowsocks-rm manyuser版能不能加个功能，把select放到memcache上读取，update流量还是在mysql上，解决锁问题？

谢谢！

**Comment by mengskysama** [comment]
看日志每次SELECT都会花很长时间，而且数据量不大，这种量的数据数据库肯定不会存在瓶颈，问题应该出在数据库上，看看show profiles

**Comment by j0hnnie** [comment]
@javacty 请问：如何设置多节点，我在搬瓦工上架设了了ss manyusers、sspanel，并且开放了mysql的远程登录，而且也把3306端口加入到iptables里了，其他还需要设置什么吗？
