### ISSUE TITLE
运行python servers.py出错

### ISSUE THREAD

**Issue by ladiesman218** [mengskysama/shadowsocks-rm#8]
运行python servers.py或者python server.py都会提示python: can't open file 'servers.py': [Errno 2] No such file or directory
菜鸟求指教，可能会是哪方面的问题？

**Comment by Cnempty** [comment]
进入目录，如cd /root/shadowsocks/shadowsocks，然后运行python servers.py
如果你想后台运行，请使用nohup python server.py > /var/log/shadowsocks.log 2>&1 &

**Comment by ladiesman218** [comment]
感谢，照方法解决了
